### PR TITLE
feature-add-the-project-structure

### PR DESCRIPTION
**Pull request by dchvs**

### CODE REVIEW

**Comment by nikhildevshatwar** [comment]
Please squash changes made to existing files
e.g. replacing the TODO commit, updating the license, etc

**Review by michaelgruner — APPROVED** [review]

**Comment by michaelgruner** [comment]
@nikhildevshatwar the PR was mistakenly closed. I cannot open it, do you mind re-opening it so we can finish the PR discussion?

**Comment by shyam-j** [comment]
@michaelgruner I was able to create a PR#2 and merge it to develop. Not sure if it was the right way.

**Comment by nikhildevshatwar** [comment]
> @nikhildevshatwar the PR was mistakenly closed. I cannot open it, do you mind re-opening it so we can finish the PR discussion?

I don't think I can reopen the PR once it is closed, the patches are merged to develop branch
I suggest you can use the develop branch for any code pushes to share amongst the team members, testing, etc
Create PRs only to master branch and I will review those

That will give you freedom to experiemet and we can review the code that goes to master branch

**Pull request closed without merging**
